dirs:
    cfg_dir : ".."

model:

glass:
    E : 0
    SE : 0
    S : 9.5
    SW : 0
    W : 0
    NW : 0
    N : 9.5
    NE : 0
    g_value : 0.7

timing:
    days_sim : 20
    interval : NEN5060
    unit : ss

thermal:
    #Envelope thermal resistance, R-value [m2/KW] (Rc_facade)
    Rc_facade : 1.3
    #Window thermal transmittance, U-value [W/m2K]
    U_glass : 2.9
    #Specific heat capacity construction [J/kgK]
    c_facade: [840, 840, 840]
    c_internal_mass: [840, 840, 840]

dimensions:
    #Envelope surface (facade + roof + ground) [m2] (A_facade)
    A_facade : 160.2
    #Floor and internal walls surface [m2]
    A_internal_mass: 170 # 106 + 64
    #Internal volume [m3]
    V_dwelling : 275.6

ventilation:
    #Ventilation, air changes per hour [#/h]
    n : 0.55
    #?????????????
    CF : 0.8

construction:
    #Facade and internal mass (floor, internal walls) construction
    # Light_weight : 0 / Middle_weight : 1  / Heavy_weight : 2
    N_facade  : 1
    N_internal_mass : 1
    #Construction thickness [m]
    th_facade: [ 0.1,  0.1, 0.2 ]
    th_internal_mass: [0.1, 0.1, 0.2]
    #Density construction in [kg/m3]
    rho_facade: [500, 1000, 2500]
    rho_internal_mass: [500, 1000, 2500]

initial:
    # density air in [kg/m3]
    rho_air : 1.20
    # specific heat capacity air [J/kgK]
    c_air  : 1005
    # to be defined
    alpha_i_facade : 8
    # to be defined
    alpha_e_facade : 23
    # to be defined
    alpha_internal_mass : 8
