dirs:
    cfg_dir : ".."

model:
timing:
    days_sim : 5
    interval : NEN5060
    unit : ss

#_______________________Dwelling temperatures calculation________________________
#   Tairdt = ((T_outdoor - Tair) / Rair_outdoor + (Twall - Tair) / Rair_wall 
#             + Qinst + Q_internal + CF * Q_solar) / Cair

#   Twalldt = ((Tair - Twall) / Rair_wall + (1 - CF) * Q_solar) / Cwall


#Calculation of the resistances.

#Resistance indoor air-wall:            Rair_wall = 1.0 / (A_internal_mass * alpha_internal_mass) 

#Resistance indoor air-outdoor air:     Rair_outdoor = 1.0 / (A_facade * U + A_glass * U_glass + qm * c_air)
#      
#       Sum of all glass surfaces:      A_glass  = g_value.sum(glass)
#          
#       U-value indoor air-facade:      U = 1.0 / (1.0 / alpha_i_facade + Rc_facade + 1 / alpha_e_facade)  
#      
#       Ventilation, mass air flow:     qm = qV * rho_air
#           
#       Ventilation, volume air flow:   qV = (n * V_dwelling) / 3600            

resistance:

#__________Resistance indoor air-wall____________
    
    #Floor and internal walls surface [m2]
    A_internal_mass: 170 # 106 + 64:
    #
    alpha_internal_mass : 8
    #Resistance indoor air-wall:
    Rair_wall: (1 / (A_internal_mass * alpha_internal_mass))

#_________Resistance indoor air-outdoor air__________
    
    #Envelope surface (facade + roof + ground) [m2] (A_facade)
    A_facade : 160.2
    
    #Envelope thermal resistance, R-value [m2/KW] (Rc_facade)
    Rc_facade : 1.3
    # to be defined
    alpha_e_facade : 23
    # to be defined
    alpha_i_facade : 8
    
    #___U-value indoor air-facade___
    U: (1 /((1 / alpha_i_facade) + (Rc_facade) + (1 / alpha_e_facade)))
    
    # glass window size and direction
    E  : 9.5
    SE : 0
    S  : 0
    SW : 0
    W  : 9.5
    NW : 0
    N  : 0
    NE : 0
    # glass transmittance
    g_value : 0.7
    
    #______Sum of all glass surfaces [m2]______
    A_glass: ((E+SE+S+SW+W+NW+N+NE)* g_value)
    
    #____Window thermal transmittance, U-value [W/m2K]___
    U_glass : 2.9
   
    #Ventilation, air changes per hour [#/h]
    n : 0.55
    #Internal volume [m3]
    V_dwelling : 275.6
    #density air in [kg/m3]
    rho_air : 1.20
    #Ventilation, volume air flow [m3/s]
    qV: (n * V_dwelling)/3600
    
    #_____Ventilation, mass air flow [kg/s]______
    qm: (qV * rho_air)
    
    #specific heat capacity air [J/kgK]
    c_air  : 1005
    #Resistance indoor air-outdoor air.
    Rair_outdoor: (1 / (A_facade * U + A_glass * U_glass + (qm * c_air)))
#

#Calculation of the capacities.

#Capacity indoor air + walls:
#   Cair = rho_internal_mass * c_internal_mass * V_internal_mass / 2.0 + rho_air * c_air * V_dwelling  

#Capacity walls: Cwall = rho_internal_mass * c_internal_mass * V_internal_mass / 2.0  # Capacity walls
#   Cwall = rho_facade * c_facade * V_facade / 2.0
#   V_facade = A_facade*th_facade  
capacity:
#__________Capacity indoor air + walls____________
    
    #Facade and internal mass (floor, internal walls) construction
    # Light_weight : 0 / Middle_weight : 1  / Heavy_weight : 2
    N_internal_mass : 1
    #Density construction in [kg/m3]
    rho_internal_mass: [500, 1000, 2500]
    #Specific heat capacity construction [J/kgK]
    c_internal_mass: [840, 840, 840]
    #Floor and internal walls surface [m2]
    A_internal_mass: 170 # 106 + 64
    #Construction thickness [m]
    th_internal_mass: [0.1, 0.1, 0.2]
    #Volume floor and internal walls construction [m3]
    V_internal_mass : (A_internal_mass * th_internal_mass)
    # density air in [kg/m3]
    rho_air : 1.20
    # specific heat capacity air [J/kgK]
    c_air  : 1005
    #Internal volume [m3]
    V_dwelling : 275.6
    #Capacity indoor air + walls
    Cair: (((rho_internal_mass[N_internal_mass] * c_internal_mass[N_internal_mass] * V_internal_mass[N_internal_mass]) / 2.0) + rho_air * c_air * V_dwelling)  

#___________Capacity walls____________________
#Facade and internal mass (floor, internal walls) construction
    # Light_weight : 0 / Middle_weight : 1  / Heavy_weight : 2
    N_facade  : 1
    #Construction thickness [m]
    th_facade: [ 0.1,  0.1, 0.2 ]
    #Specific heat capacity construction [J/kgK]
    c_facade: [840, 840, 840]
    #Density construction in [kg/m3]
    rho_facade: [500, 1000, 2500]
    #Envelope surface (facade + roof + ground) [m2] (A_facade)
    A_facade : 160.2
    #Volume facade walls construction [m3]
    V_facade : (A_facade * th_facade)
    #Capacity walls.
    Cwall: ((rho_facade[N_facade] * c_facade[N_facade] * V_facade[N_facade]) / 2.0)
    #Cwall: ((rho_internal_mass[N_facade] * c_internal_mass[N_facade] * V_internal_mass[N_facade]) / 2.0) 
    
    


    
dimensions:
    #Envelope surface (facade + roof + ground) [m2] (A_facade)
    A_facade : 160.2
    #Floor and internal walls surface [m2]
    A_internal_mass: 170 # 106 + 64
    #Internal volume [m3]
    V_dwelling : 275.6
#

thermal:
    #Envelope thermal resistance, R-value [m2/KW] (Rc_facade)
    Rc_facade : 1.3
    #Window thermal transmittance, U-value [W/m2K]
    U_glass : 2.9
    #Specific heat capacity construction [J/kgK]
    c_facade: [840, 840, 840]
    c_internal_mass: [840, 840, 840]

ventilation:
    #Ventilation, air changes per hour [#/h]
    n : 0.55
    #?????????????
    CF : 0.8

construction:
    #Facade and internal mass (floor, internal walls) construction
    # Light_weight : 0 / Middle_weight : 1  / Heavy_weight : 2
    N_facade  : 1
    N_internal_mass : 1
    #Construction thickness [m]
    th_facade: [ 0.1,  0.1, 0.2 ]
    th_internal_mass: [0.1, 0.1, 0.2]
    #Density construction in [kg/m3]
    rho_facade: [500, 1000, 2500]
    rho_internal_mass: [500, 1000, 2500]

initial:
    # density air in [kg/m3]
    rho_air : 1.20
    # specific heat capacity air [J/kgK]
    c_air  : 1005
    # to be defined
    alpha_i_facade : 8
    # to be defined
    alpha_e_facade : 23
    # to be defined
    alpha_internal_mass : 8
    

# Internal heat gain and Thermostat profile setting.
# Keep the default value unless you know what you are doing.

internal:
    # Presence from [hour]
    t1 : 8  # [time]
    
    # Presence until [hour]
    t2 : 23 # [time]
    
    # _________Work days____________:
    
    # Define wake up time in the morning 7:00, internal heat 400 [W]
    Wu_time : 7 # [time]
    
    # Go to work time/ leave the house
    # Define time that people go to work 8:00, thermostat set to 17
    Work_time : 8   # [time]
    
    #Define time that people back from work 18:00, internal heat 400 [W]
    back_home_from_work : 18 # [time]
    
    #Do not change this value except 
    #user want to add additional profile on working day. [W]
    Flex_heat_SP_workday  : 150     # [W]
    
    # _______Holidays (day-off)_________:
    
    # Define wake up time in the morning 10:00, internal heat 400 [W]
    Wu_time_dayoff : 10 # [time]
    
    # Define time that people go out for shopping 
    # in the day-off, 13:00
    shopping_time : 13  # [time]
    
    # Define heat gain setpoint when go out, 
    #change to 400 if not going out for shopping. 
    Flex_T_SP_dayoff   : 150 # [W]
    
    # Define time that people back home after shopping 15:00,
    # internal heat 400 [W]
    back_home : 15  # [time]
 
    
    # Internal heat difference between day and night [W]
    delta_Q : 150   # [W]
    # Daytime internal heat generation [W]
    Q_day : 400     # [W]
   
thermalstat_setpoint:
    # Presence from [hour] 8:00
    t1 : 8  # [time]
    
    # Presence until [hour] 23:00
    t2 : 23 # [time]
    
    # _________Work days____________:
    
    # Define wake up time in the morning 7:00 [hour], temperature set to 20
    Wu_time : 7     # [time]
    
    # Go to work time/ leave the house
    # Define time that people go to work 8:00, thermostat set to 17
    Work_time : 8   # [time]
    
    #Define time that people back from work 18:00, temperature set to 20
    back_home_from_work : 18 # [time]
    
    #Do not change this value except 
    #user want to add additional SP profile on working day.
    Flex_T_SP_workday  : 17 # degree [C]
    
    # _______Holidays (day-off)_________:
    
    # Define wake up time in the morning 10:00, temperature set to 20
    Wu_time_dayoff : 10 # [time]
    
    # Define time that people go out for shopping 
    # in the day-off, thermostat set to 18
    shopping_time : 13  # [time]
    
    # Define thermostat setpoint when go out, 
    #change to 20 if dont want to change the temperature. 
    Flex_T_SP_dayoff   : 18 # degree [C]
    
    #Define time that people back home after shopping 15:00,
    #temperature set to 20
    back_home : 15      # [time]
 
    # Set temperature of thermostat at night from time t2
    Night_T_SP : 17 # degree [C]
    
    # Set day temperature of thermostat
    Day_T_SP   : 20 # degree [C]
 

controller:
    # propotional gain
    kp : 7000
    # intergal
    ki : 0
    # derivative
    kd : 0
   

   

radiator:
    # U-value of the radiator
    Urad : 30
    # Area of the radiator
    Arad : 10
    # Cp value fo water
    cpwater : 4180
    #Volume of the radiator
    volume_rad : 50
    #Capacity of the radiator
    Crad : (volume_rad * cpwater)
    #density of the water
    rhowater : 1000
    #Capacity of the buffervessel
    Cmid : (cpwater*volumeMid*rhowater)
